import os
import matplotlib.pyplot as plt
import numpy as np
from fmpy import simulate_fmu

# --- FMU Simulation Setup ---

# Path to your FMU file
# Ensure 'CircuitInertiaFMU.fmu' is in the same directory as this script,
# or provide the full path to the FMU file.
fmu_filename = 'CircuitInertiaFMU.fmu'

# Example input table: time and valueInput
# Using the input data provided by the user
time_input_table = np.array([
    (0.0, 1.0),
    (0.5, 3.5),
    (1.0, 5.0),
    (1.5, 2.5),
    (2.0, 4.0),
], dtype=[('time', np.float64), ('valueInput', np.float64)])

# Define simulation stop time based on the last timestamp in the input table
start_time = time_input_table['time'][0] # Start time from the first input timestamp
stop_time = time_input_table['time'][-1] # Stop time from the last input timestamp

# --- Run the FMU Simulation ---
print(f"Simulating FMU: {fmu_filename} from {start_time}s to {stop_time}s...")
try:
    result = simulate_fmu(
        filename=fmu_filename,
        start_time=start_time,
        stop_time=stop_time,
        input=time_input_table, # Use the provided input table
        output=['valueOutput']
    )
    print("Simulation complete.")
except Exception as e:
    print(f"Error during FMU simulation: {e}")
    print("Please ensure 'CircuitInertiaFMU.fmu' exists and is a valid FMU.")
    print("Also check that 'valueOutput' is a valid output variable in your FMU.")
    print("Exiting because FMU simulation failed.")
    exit()

# Extract time and output values from the simulation result
time_points = [row[0] for row in result]
output_values = [row[1] for row in result]

# --- Check for Data Before Plotting ---
if not time_points or not output_values:
    print("No data was generated by the FMU simulation. Cannot create a plot.")
    print("Please check your FMU file, input, and output variable names.")
    exit()

# --- Plotting Setup ---

# Create the figure and axes for the plot
fig, ax = plt.subplots(figsize=(10, 6))

# Plot all the data at once
ax.plot(time_points, output_values, 'b-', lw=2) # 'b-' for blue line

# Set plot limits and labels
ax.set_xlim(min(time_points), max(time_points))
# Add some padding to y-axis limits, handle cases where min/max might be the same
y_min = min(output_values)
y_max = max(output_values)
if y_min == y_max: # Handle constant output
    # If min and max are the same, create a small range around the value
    padding = 0.1 * abs(y_min if y_min != 0 else 1)
    ax.set_ylim(y_min - padding, y_max + padding)
else:
    ax.set_ylim(y_min * 0.9, y_max * 1.1)
ax.set_xlabel('Time (s)')
ax.set_ylabel('valueOutput')
ax.set_title('FMU Simulation Output')
ax.grid(True)

# Display the plot
plt.show()
